package soundplay;


import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class musicApp extends javax.swing.JFrame {
long total_length;
    long pouse;
    FileInputStream FIS;
    BufferedInputStream BIS;
    Player player;
    File myFile=null;
    /**
     * Creates new form musicApp
     */
    public musicApp() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnresume = new javax.swing.JButton();
        btnplay = new javax.swing.JButton();
        btnpause = new javax.swing.JButton();
        BTNEXIT = new javax.swing.JButton();
        lblsong = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 102));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnresume.setBackground(new java.awt.Color(0, 0, 0));
        btnresume.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnresume.setForeground(new java.awt.Color(255, 255, 255));
        btnresume.setText("RESUME");
        btnresume.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnresume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnresumeMouseReleased(evt);
            }
        });
        getContentPane().add(btnresume, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, -1, 50));

        btnplay.setBackground(new java.awt.Color(0, 0, 0));
        btnplay.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnplay.setForeground(new java.awt.Color(255, 255, 255));
        btnplay.setText("PLAY");
        btnplay.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnplayMouseReleased(evt);
            }
        });
        btnplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplayActionPerformed(evt);
            }
        });
        getContentPane().add(btnplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 80, 50));

        btnpause.setBackground(new java.awt.Color(0, 0, 0));
        btnpause.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnpause.setForeground(new java.awt.Color(255, 255, 255));
        btnpause.setText("PAUSE");
        btnpause.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnpause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnpauseMouseReleased(evt);
            }
        });
        getContentPane().add(btnpause, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 80, 50));

        BTNEXIT.setBackground(new java.awt.Color(0, 0, 0));
        BTNEXIT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BTNEXIT.setForeground(new java.awt.Color(255, 255, 255));
        BTNEXIT.setText("QUIT");
        BTNEXIT.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        BTNEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEXITActionPerformed(evt);
            }
        });
        getContentPane().add(BTNEXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 90, 50));

        lblsong.setBackground(new java.awt.Color(0, 0, 0));
        lblsong.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblsong.setForeground(new java.awt.Color(255, 255, 255));
        lblsong.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblsong.setOpaque(true);
        getContentPane().add(lblsong, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 570, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\SONG.jpg")); // NOI18N
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 15, true));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 300, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\1464127661.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        getAccessibleContext().setAccessibleName("MP3 MUSIC PLAYER");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEXITActionPerformed

int P = JOptionPane.showConfirmDialog(null," Are you sure you want to exit this cool music?","Confirmation",JOptionPane.YES_NO_OPTION);
            if (P==0)
            {
             
        System.exit(0);
            }
    }//GEN-LAST:event_BTNEXITActionPerformed

    private void btnplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplayActionPerformed
    
    }//GEN-LAST:event_btnplayActionPerformed

    private void btnplayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnplayMouseReleased
                                            
    try {
        JFileChooser chooser= new JFileChooser();
        int val = chooser.showOpenDialog(null);
        if(val==JFileChooser.APPROVE_OPTION);
        {
            myFile = chooser.getSelectedFile();
            String song = myFile+"";
            String name = chooser.getSelectedFile().getName();
            lblsong.setText(name);
            
        }
        FIS =new FileInputStream(myFile);
        
        BIS =new BufferedInputStream(FIS);
        player =new Player(BIS);
        
        total_length =FIS.available();
        new Thread(){
            public void run()
            {
                
                try {
                    player.play();
                } catch (JavaLayerException ex) {
                    Logger.getLogger(musicApp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }.start();
    } catch (FileNotFoundException ex) {
        Logger.getLogger(musicApp.class.getName()).log(Level.SEVERE, null, ex);
    } catch (JavaLayerException ex) {
        Logger.getLogger(musicApp.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        Logger.getLogger(musicApp.class.getName()).log(Level.SEVERE, null, ex);
    }
       
       
 

    }//GEN-LAST:event_btnplayMouseReleased

    private void btnresumeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnresumeMouseReleased
    try {
        FIS =new FileInputStream(myFile);
        
        BIS =new BufferedInputStream(FIS);
        player =new Player(BIS);
        
        FIS.skip(total_length-pouse);
                new Thread(){
                    public void run(){
                        try {
                            player.play();
                        } catch (JavaLayerException ex) {
                            Logger.getLogger(musicApp.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }.start();
                } catch (FileNotFoundException ex) {
        Logger.getLogger(musicApp.class.getName()).log(Level.SEVERE, null, ex);
    } catch (JavaLayerException ex) {
        Logger.getLogger(musicApp.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        Logger.getLogger(musicApp.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }//GEN-LAST:event_btnresumeMouseReleased

    private void btnpauseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpauseMouseReleased
    try {
        if(player !=null)
            pouse=FIS.available();
        player.close();
    } catch (IOException ex) {
        Logger.getLogger(musicApp.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_btnpauseMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(musicApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(musicApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(musicApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(musicApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new musicApp().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNEXIT;
    private javax.swing.JButton btnpause;
    private javax.swing.JButton btnplay;
    private javax.swing.JButton btnresume;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblsong;
    // End of variables declaration//GEN-END:variables
}
